### ISSUE TITLE
Controlbar 

### ISSUE THREAD

**Issue by xguya** [videojs/videojs-playbackrate-adjuster#2]
Hello I use controlbar as:

```
  controlBar: {
        children: [
```

How I can show your plugin in Control Bar ?

**Comment by gkatsev** [comment]
This plugin doesn't produce a button on the control bar. You can see https://videojs.github.io/videojs-playbackrate-adjuster/ for an example. See https://blog.videojs.com/feature-spotlight-middleware/#Playbackrate-Adjustment-A-Case-Study for an overview.
