### ISSUE TITLE
NPM module does not work with video.js 7 when bundled, due to dependency on video.js 6

### ISSUE THREAD

**Issue by cdhowie** [videojs/videojs-playbackrate-adjuster#3]
## Description
A simple copy of the sample code bundled with webpack apparently fails to work correctly when the "host" is depending on `video.js^7` because the NPM module for this plugin depends on `video.js^6.0.0-RC.5`.  Npm therefore installs both versions, and webpack bundles both versions.  The plugin registers itself with video.js 6 but the rest of the bundle doesn't care because it's using video.js 7.

I suggest that `video.js` be made a peer dependency with semver range `^6.0.0-RC.5 || ^7`.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Install `video.js^7` and `videojs-playbackrate-adjuster`.
2. Build a small sample using the test code in the plugin readme:
     ```
     var videojs = require('video.js');
     require('videojs-playbackrate-adjuster');
     ```
3. Observe that the video duration is not appropriately adjusted when the playback speed selector is changed.

The problem is also easily discovered with `npm ls video.js` after installing both packages:

```
├─┬ video.js@7.10.2
│ └─┬ @videojs/http-streaming@2.2.4
│   └── video.js@7.10.2
└─┬ videojs-playbackrate-adjuster@1.0.0
  └── video.js@6.13.0
```

### Expected
The plugin should register with video.js and adjust the duration when the playback rate is changed.

### Actual
The duration is not adjusted when the playback rate is changed, and the middleware is apparently not registered with video.js 7 (confirmed through debugging).

## Workaround
With webpack, an alias for `video.js` can be used, forcing all instances of `require('video.js')` to use the version the host wants:

    resolve: {
        alias: {
            'video.js': path.resolve(__dirname, 'node_modules/video.js/'),
        },  
    },  

The plugin could also be manually registered with video.js 7, but this still causes all of video.js 6 to be included in the bundle, which is wasteful.

#### videojs
7.10.2

#### browsers
All, as the issue is created at bundle time.

#### OSes
All.

### plugins
None.

**Comment by gkatsev** [comment]
I just published a patch version that fixes the dependency issues.
